export const fallbackBanks = [
  { id: 'mcb', name: 'MCB Bank', fullName: 'MCB Bank Limited', color: '#8B1A2B', type: 'commercial', cssClass: 'mcb' },
  { id: 'faysal', name: 'Faysal Bank', fullName: 'Faysal Bank Limited', color: '#1E3A5F', type: 'commercial', cssClass: 'faysal' },
  { id: 'albaraka', name: 'Al Baraka', fullName: 'Al Baraka Bank Pakistan', color: '#C59B27', type: 'commercial', cssClass: 'albaraka' },
  { id: 'mcbislamic', name: 'MCB Islamic', fullName: 'MCB Islamic Bank Ltd', color: '#005A36', type: 'commercial', cssClass: 'mcbislamic' },
  { id: 'allied', name: 'Allied Bank', fullName: 'Allied Bank Limited', color: '#00447C', type: 'commercial', cssClass: 'allied' },
  { id: 'askari', name: 'Askari Bank', fullName: 'Askari Bank Limited', color: '#003976', type: 'commercial', cssClass: 'askari' },
  { id: 'bah', name: 'Bank AL Habib', fullName: 'Bank AL Habib Limited', color: '#004225', type: 'commercial', cssClass: 'bah' },
  { id: 'alfalah', name: 'Bank Alfalah', fullName: 'Bank Alfalah', color: '#ED1C24', type: 'commercial', cssClass: 'alfalah' },
  { id: 'bop', name: 'Bank of Punjab', fullName: 'The Bank of Punjab', color: '#1D4289', type: 'public', cssClass: 'bop' },
  { id: 'bankislami', name: 'BankIslami', fullName: 'BankIslami Pakistan', color: '#2E7D32', type: 'commercial', cssClass: 'bankislami' },
  { id: 'hbl', name: 'HBL', fullName: 'Habib Bank Limited', color: '#00833D', type: 'commercial', cssClass: 'hbl' },
  { id: 'habibmetro', name: 'Habib Metro', fullName: 'Habib Metropolitan Bank', color: '#004D40', type: 'commercial', cssClass: 'habibmetro' },
  { id: 'hblislamic', name: 'HBL Islamic', fullName: 'HBL Islamic Bank Limited', color: '#005930', type: 'commercial', cssClass: 'hblislamic' },
  { id: 'jsbank', name: 'JS Bank', fullName: 'JS Bank', color: '#F37021', type: 'commercial', cssClass: 'jsbank' },
  { id: 'meezan', name: 'Meezan Bank', fullName: 'Meezan Bank', color: '#00594C', type: 'commercial', cssClass: 'meezan' },
  { id: 'ubl', name: 'UBL', fullName: 'United Bank Limited (UBL)', color: '#E31837', type: 'commercial', cssClass: 'ubl' },
  { id: 'sadapay', name: 'SadaPay', fullName: 'SadaPay (Mastercard)', color: '#1ED760', type: 'digital', cssClass: 'sadapay' },
  { id: 'nayapay', name: 'NayaPay', fullName: 'NayaPay (Visa)', color: '#6C63FF', type: 'digital', cssClass: 'nayapay' },
  { id: 'easypaisa', name: 'Easypaisa', fullName: 'Easypaisa Bank / Wallet', color: '#4CAF50', type: 'digital', cssClass: 'easypaisa' },
  { id: 'jazzcash', name: 'JazzCash', fullName: 'JazzCash Wallet', color: '#E53935', type: 'digital', cssClass: 'jazzcash' },
  { id: 'sc', name: 'Standard Chartered', fullName: 'Standard Chartered Pakistan', color: '#0072AA', type: 'commercial', cssClass: 'sc' },
];

export const fallbackCategories = [
  { id: 'food', name: 'Food', emoji: '🍕', placesCount: '2656 Places', dealsCount: '3744 Deals', image: '/assets/images/category_restaurants.png', color: '#FF9500', bgColor: 'rgba(255,149,0,0.12)' },
  { id: 'lifestyle', name: 'Lifestyle', emoji: '👗', placesCount: '2787 Places', dealsCount: '326 Deals', image: '/assets/images/category_fashion.png', color: '#E91E63', bgColor: 'rgba(233,30,99,0.12)' },
  { id: 'health', name: 'Health & Labs', emoji: '🏥', placesCount: '1107 Places', dealsCount: '268 Deals', image: '/assets/images/category_shopping.png', color: '#FF2D55', bgColor: 'rgba(255,45,85,0.12)' },
  { id: 'entertainment', name: 'Entertainment', emoji: '🎬', placesCount: '407 Places', dealsCount: '231 Deals', image: '/assets/images/hero_banner.png', color: '#AF52DE', bgColor: 'rgba(175,82,222,0.12)' },
  { id: 'estores', name: 'e-Stores', emoji: '🛒', placesCount: '645 Places', dealsCount: '105 Deals', image: '/assets/images/category_electronics.png', color: '#007AFF', bgColor: 'rgba(0,122,255,0.12)' },
  { id: 'education', name: 'Education', emoji: '📚', placesCount: '291 Places', dealsCount: '70 Deals', image: '/assets/images/category_shopping.png', color: '#5AC8FA', bgColor: 'rgba(90,200,250,0.12)' },
  { id: 'homedecor', name: 'Home Decor', emoji: '🛋️', placesCount: '199 Places', dealsCount: '19 Deals', image: '/assets/images/category_shopping.png', color: '#8E8E93', bgColor: 'rgba(142,142,147,0.12)' },
  { id: 'services', name: 'Services', emoji: '✈️', placesCount: '1200 Places', dealsCount: '359 Deals', image: '/assets/images/hero_banner.png', color: '#34C759', bgColor: 'rgba(52,199,89,0.12)' },
  { id: 'electronics', name: 'Electronics', emoji: '📱', placesCount: '1789 Places', dealsCount: '19 Deals', image: '/assets/images/category_electronics.png', color: '#5856D6', bgColor: 'rgba(88,86,214,0.12)' },
  { id: 'selfcare', name: 'Self Care', emoji: '💈', placesCount: '568 Places', dealsCount: '148 Deals', image: '/assets/images/category_fashion.png', color: '#FF3B30', bgColor: 'rgba(255,59,48,0.12)' },
];

export const fallbackDeals = [
  {
    id: 'deal_kb',
    merchant: 'Kababjees BBQ & Handi',
    category: 'food',
    discount: 25,
    discountType: 'percent',
    description: '25% OFF on total bill at Kababjees Do Darya & Highway Karachi outlets using HBL, UBL or SadaPay cards',
    banksJson: JSON.stringify(['hbl', 'ubl', 'sadapay']),
    cardTypesJson: JSON.stringify(['Credit Card', 'Debit Card']),
    tiersJson: JSON.stringify(['Classic', 'Gold', 'Platinum']),
    citiesJson: JSON.stringify(['Karachi']),
    logo: '/assets/images/kababjees_logo.png',
    banner: '/assets/images/category_restaurants.png',
    validFrom: '2026-08-01',
    validTo: '2026-12-31',
    termsJson: JSON.stringify(['Present valid card at billing', 'Verified by Peekaboo Guru']),
    featured: true,
    trending: true,
    merchantColor: '#007AFF',
    merchantInitial: 'K',
  },
  {
    id: 'deal_bl',
    merchant: 'Burger Lab',
    category: 'food',
    discount: 20,
    discountType: 'percent',
    description: '20% OFF on all gourmet burgers & combos across all branches in Pakistan using Meezan Bank or NayaPay',
    banksJson: JSON.stringify(['meezan', 'nayapay', 'mcb']),
    cardTypesJson: JSON.stringify(['Credit Card', 'Debit Card']),
    tiersJson: JSON.stringify(['Gold', 'Platinum']),
    citiesJson: JSON.stringify(['Karachi', 'Lahore', 'Islamabad']),
    logo: 'https://d2liqplnt17rh6.cloudfront.net/logoImages/Logo2_b8245447-eb21-40c8-a532-21e2539b1c8a-543.gif',
    banner: 'https://d2liqplnt17rh6.cloudfront.net/coverImages/Cover_4eaef810-9c5e-4a3d-a425-7c49209687eb-734.jpeg',
    validFrom: '2026-08-01',
    validTo: '2026-12-31',
    termsJson: JSON.stringify(['Present valid card at billing']),
    featured: true,
    trending: true,
    merchantColor: '#FF9500',
    merchantInitial: 'B',
  },
  {
    id: 'deal_ch',
    merchant: 'Chughtai Diagnostic Lab',
    category: 'health',
    discount: 30,
    discountType: 'percent',
    description: '30% OFF on all lab tests & health diagnostic packages nationwide using Bank Alfalah or Askari Bank',
    banksJson: JSON.stringify(['alfalah', 'askari', 'hbl']),
    cardTypesJson: JSON.stringify(['Credit Card', 'Debit Card']),
    tiersJson: JSON.stringify(['Classic', 'Gold', 'Platinum']),
    citiesJson: JSON.stringify(['Lahore', 'Karachi', 'Islamabad', 'Rawalpindi', 'Faisalabad']),
    logo: 'https://d2liqplnt17rh6.cloudfront.net/logoImages/DVAGO2_96628ca8-715b-46e1-aa3a-4aac1522fe51-36.jpeg',
    banner: 'https://d2liqplnt17rh6.cloudfront.net/coverImages/Cover_c0718f36-1dbe-47c8-8072-c21fba8a6e3f-692.jpeg',
    validFrom: '2026-08-01',
    validTo: '2026-12-31',
    termsJson: JSON.stringify(['Valid at all Chughtai Lab collection centers']),
    featured: true,
    trending: true,
    merchantColor: '#FF2D55',
    merchantInitial: 'C',
  },
  {
    id: 'deal_dv',
    merchant: 'DVAGO Pharmacy',
    category: 'health',
    discount: 15,
    discountType: 'percent',
    description: '15% OFF on wellness products & medicines online & in-store using Easypaisa or Faysal Bank',
    banksJson: JSON.stringify(['easypaisa', 'faysal', 'ubl']),
    cardTypesJson: JSON.stringify(['Credit Card', 'Debit Card']),
    tiersJson: JSON.stringify(['Classic', 'Gold']),
    citiesJson: JSON.stringify(['Karachi', 'Lahore', 'Islamabad']),
    logo: 'https://d2liqplnt17rh6.cloudfront.net/logoImages/DVAGO2_96628ca8-715b-46e1-aa3a-4aac1522fe51-36.jpeg',
    banner: 'https://d2liqplnt17rh6.cloudfront.net/coverImages/Cover_c0718f36-1dbe-47c8-8072-c21fba8a6e3f-692.jpeg',
    validFrom: '2026-08-01',
    validTo: '2026-12-31',
    termsJson: JSON.stringify(['Valid at DVAGO pharmacies']),
    featured: false,
    trending: true,
    merchantColor: '#4CAF50',
    merchantInitial: 'D',
  }
];
